### ISSUE TITLE
Faster Scanning possible? 

### ISSUE THREAD

**Issue by its-tom-wayne** [Ashex/pokemongo-map-docker#12]
Hey Ashex, wrote you on Twitter :-)

In the DockerHub you wrote

> I've got 9 workers running right now with the no-server flag passed to them.

and I would like to know how you did this and how I can improve my map. I got the container running, but we are currently 10 to 20 people who are using this map and it would be awesome if we can improve the scanning speed. Maybe you could help me out with this?

That would be awesome - But thanks anyway for your smooth working docker-container !

Kind regard,
Tom

**Comment by Ashex** [comment]
Hey there!

I updated the readme with an example on how to do multi-user threading. Effectively the tool assigns one user per thread due to changes in the Niantic API.

**Comment by its-tom-wayne** [comment]
Hey !

Thanks a lot for the quick response. I will give it a try today and let you know if it works. I read somewhere that the multiple-accs need to have the same password, is this still so, or could they have different?

**Comment by Ashex** [comment]
It can be different passwords, the list is ordered so they have to match up with each other.
