### ISSUE TITLE
Update for new pgoapi module?

### ISSUE THREAD

**Issue by jonathanwcrane** [Ashex/pokemongo-map-docker#14]
Looks like new pgoapi module is available and is compatible with the recent API change.  

see https://github.com/keyphact/pgoapi

Will these docker images be updated?

Thanks

**Comment by Ashex** [comment]
The project the containers use was shutdown, there is a replacement that should be a drop in. I've updated the master/develop tags to pull from the new project however I haven't had a chance to properly test it.

**Comment by jonathanwcrane** [comment]
So I just tried.  When I tried 
`docker run -d -P --name pokemongo-map ashex/pokemongo-map:develop`
I got errors in the logs:

```
~ 👾  docker logs pokemongo-map
Initialized empty Git repository in /app/.git/
fatal: Couldn't find remote ref develop
Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'
npm WARN enoent ENOENT: no such file or directory, open '/app/package.json'
npm WARN app No description
npm WARN app No repository field.
npm WARN app No README data
npm WARN app No license field.
npm ERR! Linux 4.4.16-boot2docker
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run-script" "build"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! path /app/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/app/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! Please include the following file with any support request:
npm ERR!     /app/npm-debug.log
python: can't open file 'runserver.py': [Errno 2] No such file or directory
```

When I tried 
`docker run -d -P --name pokemongo-map ashex/pokemongo-map`
it fetched and successfully started a new container, but it upserted zero pokemon.

By the way, thanks so much for maintaining this repo.  You've inspired me to start learning Docker.

**Comment by Ashex** [comment]
You'll need to pull the new image first: 

`docker pull ashex/pokemongo-map:develop`

**Comment by jonathanwcrane** [comment]
Interesting.  When I said 
`docker pull ashex/pokemongo-map:develop`

I got 

```
~ 👾  docker pull ashex/pokemongo-map:develop
develop: Pulling from ashex/pokemongo-map
e110a4a17941: Already exists 
880658c84ac0: Already exists 
c8ea7b141faa: Already exists 
6f42fa1b30fe: Already exists 
f83f493a5055: Already exists 
84ff5c8cf386: Already exists 
caa4d1527efc: Pull complete 
Digest: sha256:a243c16da986f1a182acc09839eeeb7f0549f5ae8734aed897852518834284a8
Status: Downloaded newer image for ashex/pokemongo-map:develop
```

Either way, when I ran it again, it worked.  I will probably have to tweak the settings as far as scan delay and such, but nice work, @Ashex !

**Comment by Ashex** [comment]
Yup, Docker creates images in layers based off the Docker file so you only
pull the layers which changed.
