### ISSUE TITLE
Develop is broken

### ISSUE THREAD

**Issue by hemsleyk** [Ashex/pokemongo-map-docker#4]
Develop now has lots of new flags. Container no longer runs (breaking changes)

Should also add env vars and arguments for external database support.

**Comment by Ashex** [comment]
Develop is going through a huge config overhaul right now, I'll dig into this today and see how we can get it stabilised.

**Comment by Ashex** [comment]
I've added support for external database support.

I'll be overhauling how settings are passed now that configargparse is being used in the project. Basically will take environmental variables starting with POKEMON_ and inject them into config.ini which is read in. 

This drops support for passing flags to `docker run` but eliminates the need to update a script with every single flag.

That should be done tonight.
