### ISSUE TITLE
Possible to use multiple accounts in a container?

### ISSUE THREAD

**Issue by jonathanwcrane** [Ashex/pokemongo-map-docker#9]
All the instructions show passing single arguments for user, pass, etc.  Is it possible to specify multiple accounts on the develop:branch container so the search is faster?  Thanks.

**Comment by Ashex** [comment]
It's the same process. You can either do it via arguments or variables:

`--username user1,user2 --password password1,password2`

or 

``-e POKEMON_USERNAME="[{user1},{user2}]" -e POKEMON_PASSWORD="[{password1},{password2}]"`

Ignore the {}, I copied that from a script.

**Comment by Ashex** [comment]
An example has been added to the readme.
